force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Poster_URL__c.field-meta.xml
<CustomField>
    <fullName>Poster_URL__c</fullName>
    <label>Poster URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MovieCatalogController.cls
public with sharing class MovieCatalogController {
    @AuraEnabled(cacheable=true)
    public static List<String> getGenres() {
        List<String> genreOptions = new List<String>();
        for (Schema.PicklistEntry entry : Schema.SObjectType.Movie__c.fields.Genre__c.getPicklistValues()) {
            genreOptions.add(entry.getValue());
        }
        return genreOptions;
    }

    @AuraEnabled(cacheable=true)
    public static List<Movie__c> getMovies() {
        return [SELECT Id, Title__c, Rating__c, Genre__c, Poster_URL__c FROM Movie__c];
    }
}