force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/tmdb_id__c.field-meta.xml
<CustomField>
    <fullName>tmdb_id__c</fullName>
    <label>tmdb id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDBSyncDate__c.field-meta.xml
<CustomField>
    <fullName>TMDBSyncDate__c</fullName>
    <label>TMDBSyncDate__c</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TMDBSyncBatch.cls
public class TMDBSyncBatch implements Database.Batchable<SObject>, Database.Stateful {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {

        Date oneMonthAgo = Date.today().addMonths(-1);

        String query = 'SELECT Id, tmdb_id__c FROM Movie__c ' +
                       'WHERE (TMDBSyncDate__c = NULL OR TMDBSyncDate__c < :oneMonthAgo) ' +
                       'AND tmdb_id__c != NULL';
        
        return Database.getQueryLocator(query);
    }
    
    
    public void execute(Database.BatchableContext bc, List<Movie__c> scope) {
        List<Id> movieIds = new List<Id>();
        List<String> tmdbIds = new List<String>();

        for (Movie__c movie : scope) {
            movieIds.add(movie.Id);
            tmdbIds.add(movie.tmdb_id__c);
        }

        if (!tmdbIds.isEmpty()) {
            fetchMovieData.fetchMovieDataAsync(tmdbIds, movieIds);
        }
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('TMDBSyncBatch completed successfully.');
    }
}