force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/tmdb_id__c.field-meta.xml
<CustomField>
    <fullName>tmdb_id__c</fullName>
    <label>tmdb id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDBSyncDate__c.field-meta.xml
<CustomField>
    <fullName>TMDBSyncDate__c</fullName>
    <label>TMDBSyncDate__c</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MovieDataSyncBatch.cls
global class MovieDataSyncBatch implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, TMDBSyncDate__c, tmdb_id__c FROM Movie__c WHERE (TMDBSyncDate__c = NULL OR TMDBSyncDate__c < LAST_N_DAYS:30) AND tmdb_id__c != NULL';
        return Database.getQueryLocator(query);
    }
 public void execute(Database.BatchableContext bc, List<Movie__c> scope) {
    tmdb tmdbService = new tmdb();
    for (Movie__c movie : scope) {
        tmdb.tmdbMovieResponse movieDetails = tmdbService.getMovieById(movie.tmdb_id__c);
        if (movieDetails != null) {
            movie.Number__c = movieDetails.revenue;
            movie.Rating__c = movieDetails.vote_average;
            movie.Description__c = movieDetails.overview;
            movie.Title__c = movieDetails.original_title;
            movie.Budget__c = movieDetails.budget;
            movie.TMDBSyncDate__c = Date.today();
        }
    }
    update scope;
}
    public void finish(Database.BatchableContext bc) {
        System.debug('Batch Apex job completed successfully.');
    }
}