force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Script</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>Movies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/tmdb_id__c.field-meta.xml
<CustomField>
    <fullName>tmdb_id__c</fullName>
    <label>tmdb id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <label>Script</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MovieDataUploaderController.cls
public with sharing class MovieDataUploaderController {

    @AuraEnabled
    public static void parseAndCreateMovies(String contentDocumentId) {
        try {
            ContentVersion contentVersion = [SELECT VersionData FROM ContentVersion WHERE ContentDocumentId = :contentDocumentId LIMIT 1];
            Blob fileBlob = contentVersion.VersionData;
            String jsonString = fileBlob.toString();

            List<JSONImporter.MovieData> jsonList = (List<JSONImporter.MovieData>) JSON.deserialize(jsonString, List<JSONImporter.MovieData>.class);
            List<Movie__c> movies = new List<Movie__c>();
            List<Script__c> scripts = new List<Script__c>();

            for (JSONImporter.MovieData movieData : jsonList) {
                if (movieData.script != null) {
                    JSONImporter.ScriptData scriptData = movieData.script;
                    Script__c script = new Script__c();
                    script.Name = scriptData.name;
                    script.Description__c = scriptData.description;
                    scripts.add(script);
                }
            }

            if (!scripts.isEmpty()) {
                insert scripts;
            }

            for (JSONImporter.MovieData movieData : jsonList) {
                Movie__c movie = new Movie__c();
                movie.Title__c = movieData.name;
                movie.TMDB_Id__c = movieData.tmdb_id;
                movie.Genre__c = movieData.genre;
                movie.Rating__c = movieData.rating != null ? movieData.rating : null;
                movie.Budget__c = movieData.budget != null ? movieData.budget : null;
                movie.Number__c = movieData.revenue != null ? movieData.revenue : null;

                if (movieData.script != null) {
                    JSONImporter.ScriptData scriptData = movieData.script;
                    for (Script__c script : scripts) {
                        if (script.Name == scriptData.name) {
                            movie.Script__c = script.Id;
                            break;
                        }
                    }
                }

                movies.add(movie);
            }

            insert movies;

        } catch (Exception e) {
            throw new AuraHandledException('Error ' + e.getMessage());
        }
    }
}