force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenreMapper.cls
public class GenreMapper {
    public static Map<String, String> getValidGenres() {
        Map<String, String> validGenres = new Map<String, String>();
        Schema.DescribeFieldResult genreField = Movie__c.Genre__c.getDescribe();
        for (Schema.PicklistEntry entry : genreField.getPicklistValues()) {
            validGenres.put(entry.getLabel().toLowerCase(), entry.getValue());
        }
        return validGenres;
    }

    public static String mapGenres(String genreString, Map<String, String> validGenres) {
        List<String> genres = genreString.split(';');
        List<String> mappedGenres = new List<String>();
        for (String genre : genres) {
            String lowerGenre = genre.toLowerCase();
            if (validGenres.containsKey(lowerGenre)) {
                mappedGenres.add(validGenres.get(lowerGenre));
            } else {
                System.debug('Genre "' + genre + '" is not valid for the Genre__c picklist and will be ignored.');
            }
        }
        return String.join(mappedGenres, ';');
    }
}