force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/tmdb_id__c.field-meta.xml
<CustomField>
    <fullName>tmdb_id__c</fullName>
    <label>tmdb id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDBSyncDate__c.field-meta.xml
<CustomField>
    <fullName>TMDBSyncDate__c</fullName>
    <label>TMDBSyncDate__c</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/movieChoiceController.cls
public with sharing class movieChoiceController {

    @AuraEnabled(cacheable=true)
    public static List<tmdbSearchMovieResult> searchMovies(String title) {
        tmdb tmdbService = new tmdb();
        tmdbSearchMovieResponse response = tmdbService.searchMovie(title);
        
        if (response != null && response.results != null) {
            return response.results;
        }
        
        return new List<tmdbSearchMovieResult>();
    }
    
    
    
    @AuraEnabled
    public static void saveMovieData(Id movieRecordId, String tmdbId, String title, Decimal rating, String overview) {
        Movie__c movie = [SELECT Id, tmdb_id__c, TMDBSyncDate__c FROM Movie__c WHERE Id = :movieRecordId LIMIT 1];
        
        if (movie != null) {
            movie.tmdb_id__c = tmdbId;
            movie.TMDBSyncDate__c = Date.today();
            movie.Title__c = title;
            movie.Rating__c = rating;
            movie.Description__c = overview;
            update movie;
        }
    }
}