force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Script</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>Movies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/tmdb_id__c.field-meta.xml
<CustomField>
    <fullName>tmdb_id__c</fullName>
    <label>tmdb id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <label>Script</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MovieService.cls
public class MovieService {
    public static void processMovies(String jsonData, Map<String, String> validGenres, Map<String, Script__c> scriptMap, List<Movie__c> moviesToInsert) {
        JSONParser parser = JSON.createParser(jsonData);
        Integer chunkSize = 100;

        while (parser.nextToken() != null) {
            if (parser.getCurrentToken() == JSONToken.START_OBJECT) {
                JSONImporter.MovieData movieData = (JSONImporter.MovieData)parser.readValueAs(JSONImporter.MovieData.class);

                Movie__c movie = new Movie__c();
                movie.Title__c = movieData.name;
                movie.tmdb_id__c = movieData.tmdb_id;
                movie.Genre__c = GenreMapper.mapGenres(movieData.genre, validGenres);
                movie.Rating__c = movieData.rating;
                movie.Budget__c = movieData.budget;
                movie.Number__c = movieData.revenue;

                if (movieData.script != null && scriptMap.containsKey(movieData.script.id)) {
                    movie.Script__c = scriptMap.get(movieData.script.id).Id;
                }

                moviesToInsert.add(movie);

                if (moviesToInsert.size() == chunkSize) {
                    insert moviesToInsert;
                    moviesToInsert.clear();
                }
            }
        }
    }
}