force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genres</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/tmdb_id__c.field-meta.xml
<CustomField>
    <fullName>tmdb_id__c</fullName>
    <label>tmdb id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MovieTriggerTest.cls
@IsTest
public class MovieTriggerTest {

    @IsTest
    static void testMovieTrigger() {
        
        Movie__c movie1 = new Movie__c(
            tmdb_id__c = 'tmdb12345',
            Title__c = 'Test Movie 1 Title',
            Genre__c = 'Action',
            Rating__c = 8.0,
            Budget__c = 50000000,
            Number__c = 100000000
        );
        
        Movie__c movie2 = new Movie__c(
            tmdb_id__c = 'tmdb67890',
            Title__c = 'Test Movie 2 Title',
            Genre__c = 'Comedy',
            Rating__c = 6.5,
            Budget__c = 30000000,
            Number__c = 60000000
        );

        Test.startTest();
        insert new List<Movie__c>{movie1, movie2};
        Test.stopTest();
        List<AsyncApexJob> asyncJobs = [SELECT Id, Status FROM AsyncApexJob WHERE JobType = 'Future' AND ApexClass.Name = 'fetchMovieData'];
        System.assertEquals(1, asyncJobs.size(), 'There should be exactly one future job for fetchMovieDataAsync.');
    }
}